---
- name: Restart zabbix-server
  systemd:
    name: zabbix-server
    state: restarted

- name: Restart zabbix-agent
  systemd:
    name: zabbix-agent
    state: restarted

- name: Restart apache2
  systemd:
    name: apache2
    state: restarted
