---
- name: Update apt cache
  shell: apt-get update -y
  args:
    executable: /bin/bash
  changed_when: true

- name: Install Nginx
  shell: DEBIAN_FRONTEND=noninteractive apt-get install -y nginx
  args:
    executable: /bin/bash
  changed_when: true

- name: Configure Nginx load balancer
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/mediawiki
    owner: root
    group: root
    mode: '0644'
  notify: Restart nginx

- name: Enable site
  file:
    src: /etc/nginx/sites-available/mediawiki
    dest: /etc/nginx/sites-enabled/mediawiki
    state: link
  notify: Restart nginx

- name: Remove default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart nginx

- name: Ensure Nginx is running and enabled
  systemd:
    name: nginx
    state: started
    enabled: yes
